### ISSUE TITLE
Responsive photo layout 

### ISSUE THREAD

**Issue by SamsonGedefa** [SamsonGedefa/art-world#11]
Right now the images are placed randomly and don't fit the entire width of the parent which causes some rows to have 4 images and others 3, here is how it should look like:

- 4 images per row
- The images have the same height but different width
- is responsive to different screen sizes

**Comment by rec2** [comment]
Please see my pull request

**Comment by SamsonGedefa** [comment]
Nice work, I think it looks good like that for now.
